{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "authorship_tag": "ABX9TyOLGH5KWOC50twjyxO0ShsE",
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/itsnytrix/castle-thing/blob/main/Castle_Adventure_Game.py\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 4,
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 130
        },
        "id": "u5yWFWQTeP83",
        "outputId": "90b15e52-8f5e-4765-b816-33671b76460e"
      },
      "outputs": [
        {
          "output_type": "error",
          "ename": "SyntaxError",
          "evalue": "ignored",
          "traceback": [
            "\u001b[0;36m  File \u001b[0;32m\"<ipython-input-4-45cefa244a42>\"\u001b[0;36m, line \u001b[0;32m14\u001b[0m\n\u001b[0;31m    print \"\"\u001b[0m\n\u001b[0m          ^\u001b[0m\n\u001b[0;31mSyntaxError\u001b[0m\u001b[0;31m:\u001b[0m Missing parentheses in call to 'print'. Did you mean print(\"\")?\n"
          ]
        }
      ],
      "source": [
        "import math\n",
        "import time\n",
        "\n",
        "global text_delay\n",
        "text_delay = 0.5\n",
        "\n",
        "stats_array = [\"Strength\",\"Speed\",\"Endurance\",\"Agility\",\"Intellengence\",\"Luck\"]\n",
        "selected_character_stats = [\"0\",\"0\",\"0\",\"0\",\"0\",\"0\"]\n",
        "elf_stats = [\"4\",\"8\",\"5\",\"6\",\"4\",\"3\"]\n",
        "wizard_stats = [\"3\",\"3\",\"5\",\"5\",\"10\",\"4\"]\n",
        "archer_stats = [\"5\",\"3\",\"8\",\"6\",\"5\",\"3\"]\n",
        "berserker_stats = [\"9\",\"6\",\"3\",\"5\",\"4\",\"3\"]\n",
        "\n",
        "print (\"\")\n",
        "\n",
        "print (\"Character list: Elf  Wizard  Archer  Berserker\")\n",
        "\n",
        "character = raw_input(\"Select character: \")\n",
        "\n",
        "if(character == \"Elf\" or character == \"elf\"):\n",
        "      selected_character_stats[0] = elf_stats[0]\n",
        "      selected_character_stats[1] = elf_stats[1]\n",
        "      selected_character_stats[2] = elf_stats[2]\n",
        "      selected_character_stats[3] = elf_stats[3]\n",
        "      selected_character_stats[4] = elf_stats[4]\n",
        "      selected_character_stats[5] = elf_stats[5]\n",
        "\n",
        "if(character == \"Wizard\" or character == \"wizard\"):\n",
        "      selected_character_stats[0] = wizard_stats[0]\n",
        "      selected_character_stats[1] = wizard_stats[1]\n",
        "      selected_character_stats[2] = wizard_stats[2]\n",
        "      selected_character_stats[3] = wizard_stats[3]\n",
        "      selected_character_stats[4] = wizard_stats[4]\n",
        "      selected_character_stats[5] = wizard_stats[5]\n",
        "\n",
        "if(character == \"Archer\" or character == \"archer\"):\n",
        "      selected_character_stats[0] = archer_stats[0]\n",
        "      selected_character_stats[1] = archer_stats[1]\n",
        "      selected_character_stats[2] = archer_stats[2]\n",
        "      selected_character_stats[3] = archer_stats[3]\n",
        "      selected_character_stats[4] = archer_stats[4]\n",
        "      selected_character_stats[5] = archer_stats[5]\n",
        "\n",
        "if(character == \"Berserker\" or character == \"berserker\"):\n",
        "      selected_character_stats[0] = berserker_stats[0]\n",
        "      selected_character_stats[1] = berserker_stats[1]\n",
        "      selected_character_stats[2] = berserker_stats[2]\n",
        "      selected_character_stats[3] = berserker_stats[3]\n",
        "      selected_character_stats[4] = berserker_stats[4]\n",
        "      selected_character_stats[5] = berserker_stats[5]\n",
        "\n",
        "print (\"\")\n",
        "print (\"Strength:\",selected_character_stats[0])\n",
        "print (\"Speed:\",selected_character_stats[1])\n",
        "print (\"Endurance:\",selected_character_stats[2])\n",
        "print (\"Agility:\",selected_character_stats[3])\n",
        "print (\"Intellengence:\",selected_character_stats[4])\n",
        "print (\"Luck:\",selected_character_stats[5])\n",
        "\n",
        "int_stats = [0,0,0,0,0,0]\n",
        "\n",
        "int_stats[0] = int(selected_character_stats[0])\n",
        "int_stats[1] = int(selected_character_stats[1])\n",
        "int_stats[2] = int(selected_character_stats[2])\n",
        "int_stats[3] = int(selected_character_stats[3])\n",
        "int_stats[4] = int(selected_character_stats[4])\n",
        "int_stats[5] = int(selected_character_stats[5])\n",
        "\n",
        "damage = int(int_stats[0]*1.25)+(int_stats[3]/2)+(int_stats[4]*0.75)\n",
        "print (\"Damage\",damage)\n",
        "\n",
        "max_hits = int(int_stats[2]+1)\n",
        "print (\"Max Hits:\",max_hits)\n",
        "\n",
        "attack_speed = int(((int_stats[1]/2)+(int_stats[3]/2)))\n",
        "print (\"Attack Speed:\",attack_speed)\n",
        "\n",
        "print \"\"\n",
        "\n",
        "def intro():\n",
        "      print (\"------------------------\")\n",
        "      print (\"Welcome to the Catatcombs\")\n",
        "      print (\"  Be prepared to fight  \")\n",
        "      print (\"       Do not die       \")\n",
        "      print (\"------------------------\")\n",
        "\n",
        "\n",
        "#Building the rooms\n",
        "def build_rooms(north_room,east_room,south_room,west_room,current_room):\n",
        "\n",
        "      print \"\"\n",
        "      #Great Hall Room\n",
        "      if(current_room == 'Great Hall'):\n",
        "         north_room = 'Bedroom'\n",
        "         east_room = 'Dungeon'\n",
        "         south_room = 'Library'\n",
        "         west_room = 'Cellar'\n",
        "         \n",
        "      #Dungeon Room\n",
        "      if(current_room == 'Dungeon'):\n",
        "         north_room = 'none'\n",
        "         east_room = 'none'\n",
        "         south_room = 'Gallery'\n",
        "         west_room = 'Great Hall'\n",
        "         \n",
        "      #Library Room\n",
        "      if(current_room == 'Library'):\n",
        "         north_room = 'Great Hall'\n",
        "         east_room = 'Gallery'\n",
        "         south_room = 'none'\n",
        "         west_room = 'Dining Hall'\n",
        "         \n",
        "      #Celler Room\n",
        "      if(current_room == 'Cellar'):\n",
        "         north_room = 'none'\n",
        "         east_room = 'Great Hall'\n",
        "         south_room = 'Dining Hall'\n",
        "         west_room = 'none'\n",
        "         \n",
        "      #Gallery Room\n",
        "      if(current_room == 'Gallery'):\n",
        "         north_room = 'Dungeon'\n",
        "         east_room = 'none'\n",
        "         south_room = 'none'\n",
        "         west_room = 'Library'\n",
        "\n",
        "      #Dining Hall Room\n",
        "      if(current_room == 'Dining Hall'):\n",
        "         north_room = 'Cellar'\n",
        "         east_room = 'Library'\n",
        "         south_room = 'none'\n",
        "         west_room = 'none'\n",
        "\n",
        "      #Bedroom Room\n",
        "      if(current_room == 'Bedroom'):\n",
        "         north_room = 'none'\n",
        "         east_room = 'none'\n",
        "         south_room = 'Great Hall'\n",
        "         west_room = 'none'\n",
        "\n",
        "      direction_question = raw_input(\"What direction do you want to go?(North,East,South,West) \")\n",
        "      print \"\"\n",
        "      if(direction_question == 'North' or direction_question == 'north'):\n",
        "            if(north_room == 'none'):\n",
        "                  current_room = current_room\n",
        "                  print (\"No room in that direction\")\n",
        "                  build_rooms('','','','',current_room)\n",
        "            else:\n",
        "                  print (\"You have entered the\",north_room)\n",
        "                  build_rooms('','','','',north_room)\n",
        "                  \n",
        "      elif(direction_question == 'East' or direction_question == 'east'):\n",
        "            if(east_room == 'none'):\n",
        "                  current_room = current_room\n",
        "                  print (\"No room in that direction\")\n",
        "                  build_rooms('','','','',current_room)\n",
        "            else:\n",
        "                  print (\"You have entered the\",east_room)\n",
        "                  build_rooms('','','','',east_room)\n",
        "                  \n",
        "      elif(direction_question == 'South' or direction_question == 'south'):\n",
        "            if(south_room == 'none'):\n",
        "                  current_room = current_room\n",
        "                  print (\"No room in that direction\")\n",
        "                  build_rooms('','','','',current_room)\n",
        "            else:\n",
        "                  print (\"You have entered the\",south_room)\n",
        "                  build_rooms('','','','',south_room)\n",
        "                  \n",
        "      elif(direction_question == 'West' or direction_question == 'west'):\n",
        "            if(west_room == 'none'):\n",
        "                  current_room = current_room\n",
        "                  print (\"No room in that direction\")\n",
        "                  build_rooms('','','','',current_room)\n",
        "            else:\n",
        "                  print (\"You have entered the\",west_room)\n",
        "                  build_rooms('','','','',west_room)\n",
        "                  \n",
        "      else:\n",
        "            current_room = current_room\n",
        "            print (\"No room in that direction\")\n",
        "            build_rooms('','','','',current_room)\n",
        "\n",
        "intro()\n",
        "print (\"You have entered the Great Hall\")\n",
        "build_rooms('','','','','Great Hall')\n",
        "         \n",
        "         \n",
        "      \n"
      ]
    }
  ]
}